---
title: 用grid包的viewport来放置图片元素
author: 陈志荣
date: '2019-10-14'
slug: 用grid包的viewport来放置图片元素
categories:
  - R
tags: ["grid","viewport","element"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

首先画出原始图：

```{r raw_fig}
library(grid)

# Using Viewports to Display Data
escape_prop <-c(0.24, 0.28, 0.28, 0.33, 0.33, 0.32, 0.3, 0.21, 0.3, 0.28, 0.17,
    0.27, 0.21, 0.18, 0.22, 0.21, 0.19, 0.17, 0.17, 0.15, 0.25, 0.19,
    0.19, 0.22, 0.21, 0.18, 0.24, 0.23, 0.27, 0.16, 0.17, 0.22, 0.17,
    0.25, 0.19, 0.25, 0.12, 0.17, 0.22, 0.22)
nfires <-c(953, 620, 584, 839, 1415, 1180, 656, 408, 872, 965, 853,
    1492, 951, 772, 1541, 1114, 479, 860, 1166, 1208, 657, 1140,
    1223, 1275, 489, 932, 1096, 1378, 1033, 889, 1046, 818, 1213,
    782, 962, 1666, 2017, 1689, 1885, 1435)

nfirescode <- nfires/max(nfires)
index <- (1:40)/41

pushViewport(viewport(width=.9, height=.9))
pushViewport(viewport(y=.75, width=.9, height=.9))
for (i in 1:40) {
  vp <- viewport(x=index[i],y=escape_prop[i], height=.03, width=.03)
  pushViewport(vp)
  grid.circle(r=sqrt(nfirescode[i]/pi))
  upViewport()
}
grid.xaxis(at=c(0,index[c(10,20,30,40)]), label=seq(1960,2000,10))
grid.yaxis(at=seq(0,.5,.1))
grid.text("Proportion of Escaped Fires", y=.6)
```


画原件一

```{r element2}
burningtree <- function() {
  grid.rect(x=.5, y=.2, width=.2, height=.4, gp=gpar(fill="grey", col=NA))
  grid.circle(x=.5, y=.5, r=.3, gp=gpar(fill="orange", col=NA))
  pushViewport(viewport(clip="on"))
  pushViewport(viewport(x=.5, y=0, angle=45))
  grid.rect(x=.5, y=.5, width=.2, height=.2, gp=gpar(fill="grey", col=NA))
  upViewport(2)
}
pushViewport(viewport())
burningtree()
```


画原件二

```{r element1}

stickperson <- function() {
  grid.circle(x=.5, y=.8, r=.1, gp=gpar(fill="yellow"))
  grid.lines(c(.5,.5), c(.7,.2)) # vertical line for body
  grid.lines(c(.5,.7), c(.6,.7)) # right arm
  grid.lines(c(.5,.3), c(.6,.7)) # left arm
  grid.lines(c(.5,.65), c(.2,0)) # right leg
  grid.lines(c(.5,.35), c(.2,0)) # left leg
}
pushViewport(viewport())
stickperson()
```


用原件一填充图形
```{r fill1}
pushViewport(viewport(width=.9, height=.9))
pushViewport(viewport(y=.75, width=.9, height=.9))
for (i in 1:40) {
  vp <- viewport(x=index[i],y=escape_prop[i], height=nfirescode[i]/10,
                 width=.03)
  pushViewport(vp)
  burningtree() 
  upViewport()
}
grid.yaxis(at=seq(0,.5,.1))
grid.xaxis(at=c(0,index[c(10,20,30,40)]), label=seq(1960,2000,10))
grid.text("Proportion of Escaped Fires", y=.6)
```

用原件二填充图形
```{r fill2}
pushViewport(viewport(width=.9, height=.9))
pushViewport(viewport(y=.75, width=.9, height=.9))
for (i in 1:40) {
  vp <- viewport(x=index[i],y=escape_prop[i], height=nfirescode[i]/10,
                 width=.03)
  pushViewport(vp)
  stickperson()
  upViewport()
}
grid.yaxis(at=seq(0,.5,.1))
grid.xaxis(at=c(0,index[c(10,20,30,40)]), label=seq(1960,2000,10))
grid.text("Proportion of Escaped Fires", y=.6)
```
